# Shell variables
# Generated by 'wal'
wallpaper='/home/chad/Pictures/sea.png'

# Special
background='#10181e'
foreground='#d0dce4'
cursor='#d0dce4'

# Colors
color0='#10181e'
color1='#3B6A85'
color2='#48758D'
color3='#677B8B'
color4='#5F8EA6'
color5='#7DA8C1'
color6='#92B3C7'
color7='#d0dce4'
color8='#919a9f'
color9='#3B6A85'
color10='#48758D'
color11='#677B8B'
color12='#5F8EA6'
color13='#7DA8C1'
color14='#92B3C7'
color15='#d0dce4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
