--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chad/Pictures/sea.png"

-- Special
background="#10181e"
foreground="#d0dce4"
cursor="#d0dce4"

-- Colors
color0="#10181e"
color1="#3B6A85"
color2="#48758D"
color3="#677B8B"
color4="#5F8EA6"
color5="#7DA8C1"
color6="#92B3C7"
color7="#d0dce4"
color8="#919a9f"
color9="#3B6A85"
color10="#48758D"
color11="#677B8B"
color12="#5F8EA6"
color13="#7DA8C1"
color14="#92B3C7"
color15="#d0dce4"
